modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="prehistoricfauna" #mandatory
version="2.3.0" #mandatory
displayName="Prehistoric Fauna" #mandatory
credits="AGSuko, Antlion, Bastion, Baular, Coda, Corgi Taco, Obsolerus, RafaMv, Ralof, Seal, superlord9362, Weastian" #optional
authors="superlord9362, Corgi Taco, RafaMv, AlexThe668" #optional
description='''
Travel to the past to discover worlds time forgot. Bring back animals long extinct, or join their world.
'''
[[dependencies.prehistoricfauna]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
